apiVersion: v1
kind: Service
metadata:
  labels:
    run: simpleapi
  name: simpleapi
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: simpleapi
  sessionAffinity: None
  type: LoadBalancer

